### PR TITLE
Add redis cache to yardim.js with matching functionality

### PR DESCRIPTION
**Pull request by naugtur**
Did not include in other controllers yet, but should be trivial for someone who knows what they do

stats endpoint is helpful for debugging cache state now

### CODE REVIEW

**Review by anonrig — APPROVED** [review]

**Comment by anonrig** [comment]
Can you resolve the conflicts? Thank you

**Comment by anonrig** [comment]
Can you run the format and lint commands?

**Comment by naugtur** [comment]
@anonrig I fixed conflicts.
I didn't add caching to other yardim*.js controllers, analogous changes need to be made there, but I'm too sleepy to do it now.

**Comment by anonrig** [comment]
No worries. I'll take it from here. Thank you.

**Pull request merged**
